config/routes.rb
Rails.application.routes.draw do

  resources :pictures

  get 'top/do'
  get 'list/do'
  get 'area/do'
  get 'job/:id' => 'job#do'

  get 'top' => 'top#do'
  get 'topto' => 'top#login'
  get 'list' => 'list#do'
  get 'entry_complete' => 'entry_complete#do'

  get 'job/:id' => 'job#do'
  get 'entry/:id' => 'job#entry'
  get 'entry/entry/:id' => 'job#create'
  get 'job' => 'job#create_pic'
  get '/job/to_entry/:id' => 'job#to_entry'

  get 'mypage/:id' => 'mypage#do'
  get 'login/thanks' => 'mypage#thanks'
  get 'login/mypage' => 'mypage#login'
  get 'login/login' => 'mypage#create'
  post 'user/new' => 'user#new'
  get 'user' => 'user#do'
  get 'create' => 'user#create'
  get 'logout'  => 'mypage#destroy'

  get 'entry_manage/:id' => 'entry_manage#do'

  get 'admin_top' => 'admin_top#do'
  get 'admin_top' => 'admin_top#new'
  get 'admin_user' => 'admin_top#user'

  get 'edit/:id' => 'edit#index'
  post 'edit/edit/:id/thanks' => 'edit#thanks'
  get 'new_edit' => 'new_edit#index'            # 入力画面
  post 'new_edit/create' => 'new_edit#create'     # 送信完了画面
  get 'delete/:id' => 'edit#delete'
  get 'area' => 'area#do'
  get 'image_test' => 'top#image_test_form'
  post 'image_create' => 'top#image_create'

  resources :images
resources :images do
  member do
    get 'show_image'
  end
end

end

app/models/admin_top.rb
class AdminTop < ActiveRecord::Base
end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/edit.rb
class Edit < ActiveRecord::Base
  has_attached_file :photo,
  styles: { medium: "300x300>", thumb: "100x100>" },
  url:  "/images/:basename.:extension", # 画像保存先のURL先
  path: "#{Rails.root}/public/images/:basename.:extension"# サーバ上の画像保存先パス


  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image.jpg" "image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :job_users
  has_many :users, through: :job_users

  belongs_to :picture

# throughオプションによりjobs_areas経由でjobsにアクセスできるようになる(productsもN！多！)
# 具体的には、category.productsで商品にアクセスができる

end

app/models/job_user.rb
class JobUser < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/jobs_users.rb
class JobsUsers < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
end

app/models/new_edit.rb
class NewEdit < ActiveRecord::Base
  include ActiveModel::Model
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # photoをattachファイルとする。stylesで画像サイズを定義できる

 # ファイルの拡張子を指定（これがないとエラーが発生する）
 #validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
 #ファイルの保存場所指定
 # has_attached_file :photo,
 #  :styles => { medium: "300x300>", thumb: "100x100>" }, # 画像サイズを指定
 # :url  => "/assets/images/:id/:style/:basename.:extension", # 画像保存先のURL先
 # :path => "#{Rails.root}/public/assets/images/:id/:style/:basename.:extension" # サーバ上の画像保存先パス
 #  validates_attachment_content_type :photo, content_type: ['gif']
 #  # imageをattachファイルとする。stylesで画像サイズを定義できる
 has_many :jobs
 has_many :pictures, through: :jobs

  has_attached_file :photo,

  styles: { medium: "318x180!" },
	url:  "/images/:basename.:extension", # 画像保存先のURL先
  path: "#{Rails.root}/public/images/:basename.:extension"# サーバ上の画像保存先パス


  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/top.rb
class Top < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :job_users
  has_many :jobs, through: :job_users
  #~
# # User生成のタイミングでコールバック
# before_create :create_remember_token
# ~
#
# # ログイン時はSessionHelperから呼び出すことになるのでpublic
# def User.new_remember_token
#   SecureRandom.urlsafe_base64
# end
#
# # 同上
# def User.encrypt(token)
#   Digest::SHA1.hexdigest(token.to_s)
# end
#
# private
#
#   # User生成時、before_createコールバックから呼び出す。
#   def create_remember_token
#     self.remember_token = User.encrypt(User.new_remember_token)
#   end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def do
    @_current_user ||= User.find_by(id: session[:user_id])
      @user = User.find_by(id: params[:id])
  end

  def login
     if session[:user_id].present?
        flash[:success] = "ログインしました!"
        redirect_to "/mypage/#{session[:user_id]}"
    else
        flash[:danger] = 'ログインしてください'
        redirect_to "/login/mypage"
    end
  end

  def image_test_form
    @image = Image.new
    @image_all = Image.all
  end

  def image_create
    @image = Image.new
    Image.create(file: params[:pic].read, filename: params[:title])
    redirect_to 'show'
  end

  def show_image
    @image = Image.find(params[:id])
    send_data @image.file, :type => 'image/jpeg', :disposition => 'inline'
    redirect_to 'image_test'
  end
end

app/helpers/area_helper.rb
module AreaHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
  # # 渡されたユーザーでログインする
  # def log_in(user)
  #   session[:user_id] = user.id
  # end
  #
  # # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  # def current_user
  #   if @current_user.nil?
  #   @current_user = User.find_by(id: session[:user_id])
  # else
  #   @current_user
  # end
  # end
  #
  # # ユーザーがログインしていればtrue、その他ならfalseを返す
  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/new_edit_helper.rb
module NewEditHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/do.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="author" content="NOZAKI">
    <meta name="description" content="リジョブのトップページです">
    <meta name="keywords" content="リジョブ,求人,美容">
    <title>野崎研修リジョブ</title>
      <%= stylesheet_link_tag "top", :media => "all" %>
  </head>
  <body>
    <div class="header">

    <div class="header-top">
      <div class="container">
        <ul class="header-top__navi">
          <li><a href="/user">新規登録</li>
          <li><a href="/logout">ログアウト</li>
          <li><a href="/admin_top">adminログイン</li>
        </ul>
      </div>
    </div>

    <div class="header-middle container clear">
      <a class="header-middle__logo" href="/top"><img class="logo_header" src="http://auctions.c.yimg.jp/images.auctions.yahoo.co.jp/image/ra112/users/5/1/8/9/buffie1019-img600x600-1414479649tcza9m19724.jpg" alt="Logo header"></a>


      <ul class="header-middle__nav">

          <li><a href="/list" rel="nofollow"><i class="icon-paper-plane"></i>求人を探す</a></li>
          <li><a href="/mypage/entries" rel="nofollow"><i class="icon-folder"></i>応募管理</a></li>
          <li><a href="/login/thanks" class="crrent"><i class="icon-user-1"></i>マイページ</a></li>
      </ul>

        </div>
      </div>

<div class="key-visual-top">
  <img class="happyhappy2016" src="https://d13yacurqjgara.cloudfront.net/users/213309/screenshots/2432274/happy2016_1x.png" alt="happyhappy2016">
</div>

<div class="content">
<br><h1 class="txt_size_18 mb_30">nozakiyukohappyhappy2016</h1>
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>
</div>


<div class="content mt_30">
  <div class="content-main">
        <section class="box-pt1 mb_20">
              <div class="heading2-pt2 heading2-pt2--border-bt">
                <h2>求人一覧ページへ</h2>
              </div>
              <dl class="list-dl-pt3 list-dl-pt3--dt14em txt_size_12">
                  <dt>
                    <span class="icon-right-dir"></span>美容
                  </dt>
                  <dd>
                    <ul class="ul-inline ul-inline--cut">
                        <li>
                          <a href="/list">▷▷一覧へ</a>
                        </li>
                      </dl>
            </section>
            <section class="box-pt1 mb_20">
                      <div class="heading2-pt2 heading2-pt2--border-bt">
                        <h2>ピックアップ求人</h2>
                      </div>
                      <div class="row row-mg mb_20">

                          <div class="cols_4 boxset-pt1">
                            <a href="/job/11">
                                <figure><img src="https://s3-ap-northeast-1.amazonaws.com/rejob-v2-images-production/files/client_shop_image/kiayTp/LwmDLP/dJBBb3/7ZPKX7/qFs/recommend.jpg?1456278400" alt=""></figure>
                              <h3 class="boxset-pt1__title">
                                『★未経験も充実した研修で安心。一緒に働きましょう♪』<br>今までの経験を活かしたい方も未経験者の方でも、是非ご応募お待ちしております☆ *充実の研修制度* 転職される方や、ブランクがある方でもご安心ください!
                              </h3>
                            </a>
                            <p class="boxset-pt1__corp"></p>
                            <dl class="boxset-pt1__terms">
                              <dt>勤務地</dt>
                              <dd>
                                愛知県
                              </dd>
                              <dt>職種</dt>
                              <dd>
                                エステティシャン
                              </dd>
                            </dl>
                          </div>

                          <div class="cols_4 boxset-pt1">
                            <a href="/job/14">
                                <figure><img src="https://s3-ap-northeast-1.amazonaws.com/rejob-v2-images-production/files/client_shop_image/iY5pYN/T39Ilu/qta0Dv/0Ajupf/1p0/recommend.jpg?1458010645" alt=""></figure>
                              <h3 class="boxset-pt1__title">
                                『スタッフ達にものすごく大人気の☆自由シフト制☆(^^♪』<br>オープンしてもうすぐ1年のお店ですが、スタッフ同士がとっても仲良しなので、日々楽しく働けますよ。(^^♪
                              </h3>
                            </a>
                            <p class="boxset-pt1__corp"></p>
                            <dl class="boxset-pt1__terms">
                              <dt>勤務地</dt>
                              <dd>
                                長野
                              </dd>
                              <dt>職種</dt>
                              <dd>
                                美容師
                              </dd>
                            </dl>
                          </div>
                      </div>
                    </section>
    </div>

    <div class="content-side">
      <section class="box-side-nav box-side-nav--admission mb_20">
          <div class="img_addmission">求人数　業界最大級！<br>\ 五分で登録完了 /</div>
          <a href="/user" class="btn btn--pt1 btn--large w-block txt_size_16"><i class="icon-user"></i> 無料会員登録 </a>
        </section>
      <section class="box-side-nav">
        <h2 class="box-side-nav__heading"><i class="icon-calendar"></i> 本日のhappyhappy2016</h2>
        <p class="t_right txt_size_12">掲載求人 <span class="txt_size_26 rj_typo_color-c"><%= Job.count %></span> 件
          <br> 登録者数 <span class="txt_size_26 rj_typo_color-c"><%= User.count %></span> 人
        </p>
        <p class="t_right txt_size_10">2016/06/01（現在）</p>
      </section>
    </div>
  </div>

<footer>
  <div class="footer">
    <div class="container">
      <div class="row row-mg footer--content">
        <div class="cols_6 f_left">
          <dl class="footer-nav">
            <dt><a href="https://relax-job.com/biyo">美容</a></dt>
            <dd>
              <ul class="ul-inline ul-inline--col5 ul--p_tb2">
                <li><a href="https://relax-job.com/esthe">エステ</a></li>
                <li><a href="https://relax-job.com/nail">ネイル</a></li>
                <li><a href="https://relax-job.com/eyelist">アイリスト</a></li>
                <li><a href="https://relax-job.com/biyoshi">美容師</a></li>
                <li><a href="https://relax-job.com/biyobuin">美容部員</a></li>
              </ul>
            </dd>



          <dl class="footer-nav">
            <dt>企業様メニュー</dt>
            <dd>
              <ul class="ul-list-none ul--p_tb2">
                <li><a href="admin_top" target="_blank">企業様ログイン</a></li>
              </ul>
            </dd>
            <dt>happyhappy2016について</dt>
            <dd>
              <ul class="ul-list-none ul--p_tb2">
                <li><a href="http://facebook.com/yuko6363" target="_blank">会社概要</a></li>

              </ul>
            </dd>
          </dl>

        <div class="cols_3 f_left">
          <a class="footer--content__bunner" href="/lp/new_inquiry">
            <img class="" src="https://s-media-cache-ak0.pinimg.com/236x/00/29/89/00298943ae0def6217c00bc1a269d8e0.jpg" alt="Img footerbunner">
          </a>
        </div>
      </div>
    </div>
    <div class="copyright">
      <div class="container t_left">
        <small>© happyhappy2016 Co.,Ltd. All Rights Reserved.</small>
      </div>
    </div>
  </div>
</footer>


  <div>
    <a href="image_test">テスト</a>
  </div>
  </body>
</html>

app/views/top/image_test_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>イメージテスト</title>
      <%= stylesheet_link_tag "top", :media => "all" %>
  </head>
  <body>

    <form method="post" action="image_create" enctype="multipart/form-data">
      <input name="authenticity_token" type="hidden" value="1234" />

    画像名 <input type="text" name="title" size="50"></p>
    <br>
     画像ファイル<input type="file" name="pic">

    <button type="submit">作成</button>
    </form>


  </body>
</html>

app/views/top/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>イメージテスト</title>
      <%= stylesheet_link_tag "top", :media => "all" %>
  </head>
  <body>
    <% @image_all.each do |image| %>
    <%= image.filename %>
    <%= image_tag show_image_image_path(image), class: "middle-img" %>
    <% end %>
    <%= image_tag show_image_image_path(image), class: "large-img" %>

  </body>
</html>