config/routes.rb
Rails.application.routes.draw do

  resources :pictures

  get 'top/do'
  get 'list/do'
  get 'area/do'
  get 'job/:id' => 'job#do'

  get 'top' => 'top#do'
  get 'topto' => 'top#login'
  get 'list' => 'list#do'
  get 'entry_complete' => 'entry_complete#do'

  get 'job/:id' => 'job#do'
  get 'entry/:id' => 'job#entry'
  get 'entry/entry/:id' => 'job#create'
  get 'job' => 'job#create_pic'
  get '/job/to_entry/:id' => 'job#to_entry'

  get 'mypage/:id' => 'mypage#do'
  get 'login/thanks' => 'mypage#thanks'
  get 'login/mypage' => 'mypage#login'
  get 'login/login' => 'mypage#create'
  post 'user/new' => 'user#new'
  get 'user' => 'user#do'
  get 'create' => 'user#create'
  get 'logout'  => 'mypage#destroy'

  get 'entry_manage/:id' => 'entry_manage#do'

  get 'admin_top' => 'admin_top#do'
  get 'admin_top' => 'admin_top#new'
  get 'admin_user' => 'admin_top#user'

  get 'edit/:id' => 'edit#index'
  post 'edit/edit/:id/thanks' => 'edit#thanks'
  get 'new_edit' => 'new_edit#index'            # 入力画面
  post 'new_edit/create' => 'new_edit#create'     # 送信完了画面
  get 'delete/:id' => 'edit#delete'
  get 'area' => 'area#do'
  get 'image_test' => 'top#image_test_form'
  post 'image_create' => 'top#image_create'

  resources :images
resources :images do
  member do
    get 'show_image'
  end
end

end

app/models/admin_top.rb
class AdminTop < ActiveRecord::Base
end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/edit.rb
class Edit < ActiveRecord::Base
  has_attached_file :photo,
  styles: { medium: "300x300>", thumb: "100x100>" },
  url:  "/images/:basename.:extension", # 画像保存先のURL先
  path: "#{Rails.root}/public/images/:basename.:extension"# サーバ上の画像保存先パス


  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image.jpg" "image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :job_users
  has_many :users, through: :job_users

  belongs_to :picture

# throughオプションによりjobs_areas経由でjobsにアクセスできるようになる(productsもN！多！)
# 具体的には、category.productsで商品にアクセスができる

end

app/models/job_user.rb
class JobUser < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/jobs_users.rb
class JobsUsers < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
end

app/models/new_edit.rb
class NewEdit < ActiveRecord::Base
  include ActiveModel::Model
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # photoをattachファイルとする。stylesで画像サイズを定義できる

 # ファイルの拡張子を指定（これがないとエラーが発生する）
 #validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
 #ファイルの保存場所指定
 # has_attached_file :photo,
 #  :styles => { medium: "300x300>", thumb: "100x100>" }, # 画像サイズを指定
 # :url  => "/assets/images/:id/:style/:basename.:extension", # 画像保存先のURL先
 # :path => "#{Rails.root}/public/assets/images/:id/:style/:basename.:extension" # サーバ上の画像保存先パス
 #  validates_attachment_content_type :photo, content_type: ['gif']
 #  # imageをattachファイルとする。stylesで画像サイズを定義できる
 has_many :jobs
 has_many :pictures, through: :jobs

  has_attached_file :photo,

  styles: { medium: "318x180!" },
	url:  "/images/:basename.:extension", # 画像保存先のURL先
  path: "#{Rails.root}/public/images/:basename.:extension"# サーバ上の画像保存先パス


  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/top.rb
class Top < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :job_users
  has_many :jobs, through: :job_users
  #~
# # User生成のタイミングでコールバック
# before_create :create_remember_token
# ~
#
# # ログイン時はSessionHelperから呼び出すことになるのでpublic
# def User.new_remember_token
#   SecureRandom.urlsafe_base64
# end
#
# # 同上
# def User.encrypt(token)
#   Digest::SHA1.hexdigest(token.to_s)
# end
#
# private
#
#   # User生成時、before_createコールバックから呼び出す。
#   def create_remember_token
#     self.remember_token = User.encrypt(User.new_remember_token)
#   end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    @picture.save
    redirect_to '/pictures'
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def picture_params
      params.require(:picture).permit(:name,:photo)
    end



end

app/helpers/area_helper.rb
module AreaHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
  # # 渡されたユーザーでログインする
  # def log_in(user)
  #   session[:user_id] = user.id
  # end
  #
  # # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  # def current_user
  #   if @current_user.nil?
  #   @current_user = User.find_by(id: session[:user_id])
  # else
  #   @current_user
  # end
  # end
  #
  # # ユーザーがログインしていればtrue、その他ならfalseを返す
  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/new_edit_helper.rb
module NewEditHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture, :multipart => true do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>
<p>
   <strong>Picture:</strong>
   <!--- Modelのstyleで指定した :midium など渡すことでサイズを指定できる -->
   <%= image_tag @picture.photo.url(:medium) %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>